on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {elixir-version: '1.15', otp-version: '25'}
          - {elixir-version: '1.15', otp-version: '26'}
          - {elixir-version: '1.18', otp-version: '27'}
          - {elixir-version: '1.19', otp-version: '28'}
          - {elixir-version: '1.20', otp-version: '29'}

    name: Tests
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir-version }}
          otp-version: ${{ matrix.otp-version }}

      - run: mix deps.get

      - run: mix compile --warnings-as-errors
        if: matrix.otp-version == '28'

      - run: mix format --check-formatted
        if: matrix.otp-version == '28'

      - run: mix test
